name: Publish to Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: |
          sudo timedatectl set-timezone Europe/Berlin
          timedatectl
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Java 11 JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: 'gradle'
          check-latest: true
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Publish to GitHub Packages
          uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
          with:
            arguments: publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
